version: "2"
linters:
  default: all
  disable:
    - dogsled
    - embeddedstructfieldcheck
    - err113
    - errname
    - exhaustive
    - exhaustruct
    - exhaustruct_v5
    - forcetypeassert
    - funcorder
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - godox
    - gomodguard
    - gosmopolitan
    - inamedparam
    - ireturn
    - mnd
    - nakedret
    - nlreturn
    - noinlineerr
    - nonamedreturns
    - paralleltest
    - prealloc
    - recvcheck
    - testpackage
    - thelper
    - unparam
    - varnamelen
    - whitespace
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    cyclop:
      max-complexity: 30
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - nikand.dev/go/json2
            - nikand.dev/go/skip
    dupl:
      threshold: 100
    gocognit:
      min-complexity: 30
    goconst:
      min-len: 2
      min-occurrences: 4
    gocritic:
      disabled-checks:
        - appendAssign
        - builtinShadow
        - commentedOutCode
        - equalFold
        - octalLiteral
        - ptrToRefParam
        - unnamedResult
        - whyNoLint
        - yodaStyleExpr
      enabled-tags:
        - experimental
        - performance
        - style
    lll:
      line-length: 170
    revive:
      rules:
        - name: unused-parameter
          disabled: true
    staticcheck:
      checks:
        - all
        - -QF1008
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - godoclint
          - lll
          - staticcheck
        path: benchmarks_data
      - linters:
          - goconst
        path: (.*)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - nikand.dev/go/json2
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
